In [1]:
#  question for mid exam

In [2]:
import numpy as np

In [7]:
data = np.array([1,2,3,4,5,6,3,6,97,3,6,8,9,400])


q1 = np.percentile(data,25)
q2 = np.percentile(data,50)
q3 = np.percentile(data,75)
# q1
# q2
q3

np.float64(7.5)

In [8]:
import pandas as pd

In [ ]:
df = pd.DataFrame(data) # this is not the proffesional way
df

      0
0     1
1     2
2     3
3     4
4     5
5     6
6     3
7     6
8    97
9     3
10    6
11    8
12    9
13  400

In [ ]:
df = pd.DataFrame({"values": data})  #converting data into pandas
# df.info()
df.describe()

           values
count   14.000000
mean    39.500000
std    106.659595
min      1.000000
25%      3.000000
50%      5.500000
75%      7.500000
max    400.000000

In [16]:
q1 = df.quantile(0.25)    # we use quantile for pandas and persantile for numpy 
q2 = df.quantile(0.50)
q3 = df.quantile(0.75)

q3

values    7.5
Name: 0.75, dtype: float64

In [ ]:
IQR = q3-q1 #
IQR

values    4.5
dtype: float64

In [ ]:
lower = q1-IQR*0.25
upper = q3+IQR*0.75

values    1.875
dtype: float64

In [ ]:
lower = q1-IQR*0.25 # To find lower bound we use the formula . number 0.25, 0.50, 0.75
upper = q3+IQR*0.75 # To find upper bound we use the formula
upper

values    10.875
dtype: float64

In [21]:
lower = q1-IQR*0.50
lower

values    0.75
dtype: float64

In [ ]:
df = pd.read_csv("CO2 Emissions_Canada.csv")
df

,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
0,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...
7380,VOLVO,XC40 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,10.7,7.7,9.4,30,219
7381,VOLVO,XC60 T5 AWD,SUV - SMALL,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7382,VOLVO,XC60 T6 AWD,SUV - SMALL,2.0,4,AS8,Z,11.7,8.6,10.3,27,240
7383,VOLVO,XC90 T5 AWD,SUV - STANDARD,2.0,4,AS8,Z,11.2,8.3,9.9,29,232
7384,VOLVO,XC90 T6 AWD,SUV - STANDARD,2.0,4,AS8,Z,12.2,8.7,10.7,26,248

In [29]:
df.describe()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km)
count,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000,7385.000000
mean,3.160068,5.615030,12.556534,9.041706,10.975071,27.481652,250.584699
std,1.354170,1.828307,3.500274,2.224456,2.892506,7.231879,58.512679
min,0.900000,3.000000,4.200000,4.000000,4.100000,11.000000,96.000000
25%,2.000000,4.000000,10.100000,7.500000,8.900000,22.000000,208.000000
50%,3.000000,6.000000,12.100000,8.700000,10.600000,27.000000,246.000000
75%,3.700000,6.000000,14.600000,10.200000,12.600000,32.000000,288.000000
max,8.400000,16.000000,30.600000,20.600000,26.100000,69.000000,522.000000

In [26]:
q1 = df.quantile(0.25)
q2 = df.quantile(0.50)
q3 = df.quantile(0.75)

TypeError: unsupported operand type(s) for -: 'str' and 'str'